import React from 'react';

const cardImages = [
    {src: './assets/images/2.svg'},
    {src: './assets/images/2-1.svg'},
    {src: './assets/images/2-2.svg'},
    {src: './assets/images/2-3.svg'},
    {src: './assets/images/3.svg'},
    {src: './assets/images/3-1.svg'},
    {src: './assets/images/3-2.svg'},
    {src: './assets/images/3-3.svg'},
    {src: './assets/images/4.svg'},
    {src: './assets/images/4-1.svg'},
    {src: './assets/images/4-2.svg'},
    {src: './assets/images/4-3.svg'},
    {src: './assets/images/5.svg'},
    {src: './assets/images/5-1.svg'},
    {src: './assets/images/5-2.svg'},
    {src: './assets/images/5-3.svg'},
    {src: './assets/images/6.svg'},
    {src: './assets/images/6-1.svg'},
    {src: './assets/images/6-2.svg'},
    {src: './assets/images/6-3.svg'},
    {src: './assets/images/7.svg'},
    {src: './assets/images/7-1.svg'},
    {src: './assets/images/7-2.svg'},
    {src: './assets/images/7-3.svg'},
    {src: './assets/images/8.svg'},
    {src: './assets/images/8-1.svg'},
    {src: './assets/images/8-2.svg'},
    {src: './assets/images/8-3.svg'},
    {src: './assets/images/9.svg'},
    {src: './assets/images/9-1.svg'},
    {src: './assets/images/9-2.svg'},
    {src: './assets/images/9-3.svg'},
    {src: './assets/images/10.svg'},
    {src: './assets/images/10-1.svg'},
    {src: './assets/images/10-2.svg'},
    {src: './assets/images/10-3.svg'},
    {src: './assets/images/A.svg'},
    {src: './assets/images/A-1.svg'},
    {src: './assets/images/A-2.svg'},
    {src: './assets/images/A-3.svg'},
    {src: './assets/images/J.svg'},
    {src: './assets/images/J-1.svg'},
    {src: './assets/images/J-2.svg'},
    {src: './assets/images/J-3.svg'},
    {src: './assets/images/Q.svg'},
    {src: './assets/images/Q-1.svg'},
    {src: './assets/images/Q-2.svg'},
    {src: './assets/images/Q-3.svg'},
    {src: './assets/images/K.svg'},
    {src: './assets/images/K-1.svg'},
    {src: './assets/images/K-2.svg'},
    {src: './assets/images/K-3.svg'},
    {src: './assets/images/Joker_1.svg'},
    {src: './assets/images/Joker-2.svg'},
    {src: './assets/images/Card_Back.svg'},
  ]

  export default cardImages;