import React from 'react';

const cardImages = [
    {src: './assets/images/2.png'},
    {src: './assets/images/2-1.png'},
    {src: './assets/images/2-2.png'},
    {src: './assets/images/2-3.png'},
    {src: './assets/images/3.png'},
    {src: './assets/images/3-1.png'},
    {src: './assets/images/3-2.png'},
    {src: './assets/images/3-3.png'},
    {src: './assets/images/4.png'},
    {src: './assets/images/4-1.png'},
    {src: './assets/images/4-2.png'},
    {src: './assets/images/4-3.png'},
    {src: './assets/images/5.png'},
    {src: './assets/images/5-1.png'},
    {src: './assets/images/5-2.png'},
    {src: './assets/images/5-3.png'},
    {src: './assets/images/6.png'},
    {src: './assets/images/6-1.png'},
    {src: './assets/images/6-2.png'},
    {src: './assets/images/6-3.png'},
    {src: './assets/images/7.png'},
    {src: './assets/images/7-1.png'},
    {src: './assets/images/7-2.png'},
    {src: './assets/images/7-3.png'},
    {src: './assets/images/8.png'},
    {src: './assets/images/8-1.png'},
    {src: './assets/images/8-2.png'},
    {src: './assets/images/8-3.png'},
    {src: './assets/images/9.png'},
    {src: './assets/images/9-1.png'},
    {src: './assets/images/9-2.png'},
    {src: './assets/images/9-3.png'},
    {src: './assets/images/10.png'},
    {src: './assets/images/10-1.png'},
    {src: './assets/images/10-2.png'},
    {src: './assets/images/10-3.png'},
    {src: './assets/images/A.png'},
    {src: './assets/images/A-1.png'},
    {src: './assets/images/A-2.png'},
    {src: './assets/images/A-3.png'},
    {src: './assets/images/J.png'},
    {src: './assets/images/J-1.png'},
    {src: './assets/images/J-2.png'},
    {src: './assets/images/J-3.png'},
    {src: './assets/images/Q.png'},
    {src: './assets/images/Q-1.png'},
    {src: './assets/images/Q-2.png'},
    {src: './assets/images/Q-3.png'},
    {src: './assets/images/K.png'},
    {src: './assets/images/K-1.png'},
    {src: './assets/images/K-2.png'},
    {src: './assets/images/K-3.png'},
    {src: './assets/images/Joker_1.png'},
    {src: './assets/images/Joker-2.png'},
    {src: './assets/images/Card_Back.png'},
  ]

  export default cardImages;